spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Bug-Tracker
  mail:
    host: smtp.gmail.com
    port: 465
    username: drakedraganeel@gmail.com
    password: your-app-password
    protocol: smtps  # Notice 'smtps' for secure SMTP
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        smtps:
          ssl:
            enable: true
          connectiontimeout: 5000  # Timeout in milliseconds
          timeout: 5000            # Socket read timeout
          writetimeout: 5000
logging:
    level:
      org.springframework.mail: DEBUG
      com.sun.mail: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
      org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
server:
  port: 8080
