spring:
  data:
    mongodb:
      uri: "mongodb+srv://bug_tracker:bug_tracker@bugtracker.hc6snqa.mongodb.net/"
      database: bug_tracker
  mail:
    host: smtp.gmail.com
    port: 465
    username: saisampathgade@gmail.com
    password: ulipkabqiphwgzjc
    protocol: smtps # Notice 'smtps' for secure SMTP
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        smtps:
          ssl:
            enable: true
          connectiontimeout: 5000 # Timeout in milliseconds
          timeout: 5000 # Socket read timeout
          writetimeout: 5000
logging:
  level:
    org.springframework.mail: DEBUG
    com.sun.mail: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
server:
  port: 8080
