spring:
  data:
    mongodb:
      host: mongodb://localhost:27017
      database: yourDatabaseName

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
